# ----
# Site

title: Test documentation
description: Test description
# url: https://cloudcannon.com
# disqus_shortname: cloudcannon
baseurl: https://siwmeckelborg.github.io/Documents/

active_sibling:
main_url:
# google_site_verification: GkBrJRSQqF43wQVGLUeUJFTPBldtIXGCw9toqvS2o_o
permalink: pretty


plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
